include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    sort_pub_dependencies: false
    library_private_types_in_public_api: false
    lines_longer_than_80_chars: false
    depend_on_referenced_packages: false
    public_member_api_docs: false